import { Doc } from "../../crdtTypes/doc.js";
import { expect, test, describe } from "vitest";
import { MAP_SET_OP } from "../../eventGraph/eventGraph.js";

describe("Path Traversal and Conflict Resolution", () => {
	test("handles concurrent assignment of primitive and nested container to the same path (container wins)", () => {
		const doc1 = new Doc("replica-1");
		const doc2 = new Doc("replica-2");

		// Replica 1 assigns a primitive to "a"
		const ev1 = doc1.getMap().set("a", "primitive-value");

		// Replica 2 assigns a nested container to "a" by accessing it implicitly
		doc2.getMap().getMap("a").set("b", "nested-value");
		const doc2Events = doc2.egWalker.graph.getSortedEvents().filter(e => e.replicaId === "replica-2");

		// Integrate
		doc2.egWalker.integrateRemote([ev1]);
		doc1.egWalker.integrateRemote(doc2Events);

		// "replica-2" > "replica-1", so the container created by doc2 should win.
		expect(doc1.getMap().toJSON()).toEqual({ a: { crdtType: "YMap", data: { b: "nested-value" } } });
		expect(doc1.getMap().toJSON()).toEqual(doc2.getMap().toJSON());
	});

	test("handles concurrent assignment of primitive and nested container to the same path (primitive wins)", () => {
		const doc3 = new Doc("replica-3");
		const doc4 = new Doc("replica-4");

		// Replica 4 assigns a primitive to "x"
		const ev4 = doc4.getMap().set("x", 42);

		// Replica 3 accesses array at "x" and inserts
		doc3.getMap().getArray("x").insert(0, ["item"]);
		const doc3Events = doc3.egWalker.graph.getSortedEvents().filter(e => e.replicaId === "replica-3");

		// Integrate
		doc4.egWalker.integrateRemote(doc3Events);
		doc3.egWalker.integrateRemote([ev4]);

		// "replica-4" > "replica-3", so doc4's primitive wins.
		expect(doc3.getMap().toJSON()).toEqual({ x: 42 });
		expect(doc3.getMap().toJSON()).toEqual(doc4.getMap().toJSON());
	});

	test("handles assignment to array element that is a primitive", () => {
		const doc1 = new Doc("replica-1");
		const doc2 = new Doc("replica-2");

		// Insert a primitive into an array
		doc1.getMap().getArray("arr").insert(0, ["primitive"]);
		const evs1 = doc1.egWalker.graph.getSortedEvents().filter(e => e.replicaId === "replica-1");
		doc2.egWalker.integrateRemote(evs1);

		// doc2 tries to access the element as an array, but wait, path traversal directly into array elements
		// isn't typically generated by our APIs unless we construct a raw event.
		// However, we can simulate an event that traverses into the primitive.
		const op = {
			type: 3, // ARRAY_INSERT_OP = 3 (wait, we can just use doc2.egWalker.localOp directly)
			path: ["arr", 0], // Traverse into the array element at index 0
			afterId: null,
			values: ["nested"]
		};
		
		// Wait, ARRAY_INSERT_OP from eventGraph
		// Let's use any op to traverse:
		doc2.egWalker.localOp({
			type: MAP_SET_OP,
			path: ["arr", 0, "foo"], // Traverses into arr[0], which is primitive "primitive", then fails to find "foo" inside "primitive"
			key: "nested",
			value: 123
		} as any);

		// It should not throw.
		const evs2 = doc2.egWalker.graph.getSortedEvents().filter(e => e.replicaId === "replica-2");
		
		// Integrate back to doc1
		doc1.egWalker.integrateRemote(evs2);
		
		// Should converge
		expect(doc1.getMap().toJSON()).toEqual(doc2.getMap().toJSON());
	});
});
